package com.example.CallCenter;

public final class PublicacionCatalog {
    private static final String DEFAULT_URL = "#";

    private PublicacionCatalog() {
    }

    public static PublicacionConfig disenadorGraficoDefault() {
        PublicacionConfig config = base(
                "disenador-grafico-contenido-digital",
                "Diseño",
                "Vacante Disponible: Diseñador Gráfico y Creador de Contenido Digital 📱",
                "Lleva tu creatividad al siguiente nivel",
                "🎨",
                "Imagen destacada de diseñador gráfico y creador de contenido digital");
        config.setCierrePostulacion("Consulta el enlace de postulación disponible al final de esta publicación y envía tu candidatura.");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Lleva tu creatividad al siguiente nivel</h2><p>Actualmente, las empresas buscan profesionales capaces de conectar con su audiencia a través de contenido visual atractivo y estrategias digitales efectivas. Por ello, la posición de Diseñador Gráfico y Creador de Contenido Digital se ha convertido en una de las más demandadas dentro del entorno digital.</p><p>Si te apasiona el diseño, disfrutas crear contenido para redes sociales y te interesa participar en proyectos creativos con impacto real, esta puede ser una excelente oportunidad para impulsar tu carrera profesional.</p></section>
            <section class="job-section"><h2>¿Qué actividades realizarás? 💡</h2><p>Como parte del equipo creativo, participarás en el desarrollo de materiales visuales y contenido digital para fortalecer la presencia de marcas, productos o servicios en diferentes plataformas.</p><ul class="job-list check-list"><li>Diseño de publicaciones para redes sociales.</li><li>Creación de contenido visual para campañas publicitarias.</li><li>Desarrollo de piezas gráficas para medios digitales e impresos.</li><li>Edición básica o avanzada de videos para plataformas digitales.</li><li>Adaptación de contenido para distintos formatos y canales de comunicación.</li><li>Colaboración con equipos de marketing, comunicación y publicidad.</li><li>Apoyo en el desarrollo de identidad visual y branding.</li><li>Investigación de tendencias creativas y formatos digitales innovadores.</li></ul></section>
            <section class="job-section"><h2>Perfil que buscan las empresas 👩‍💻</h2><p>Las organizaciones suelen buscar personas creativas, organizadas y con capacidad para transformar ideas en contenido visual atractivo.</p><h3>Formación académica</h3><ul class="job-list"><li>Estudios en Diseño Gráfico, Comunicación Visual, Marketing, Publicidad o carreras relacionadas.</li><li>Cursos o certificaciones en diseño digital, edición audiovisual o marketing digital serán valorados positivamente.</li></ul><h3>Experiencia</h3><ul class="job-list"><li>Experiencia en diseño gráfico o creación de contenido digital.</li><li>Manejo de proyectos para redes sociales, campañas publicitarias o branding.</li><li>Portafolio con trabajos que demuestren creatividad y capacidad técnica.</li></ul></section>
            <section class="job-section"><h2>Conocimientos y herramientas valoradas 🧰</h2><p>Dependiendo de la vacante, pueden solicitarse conocimientos en:</p><ul class="job-list job-related-list"><li>Adobe Photoshop.</li><li>Adobe Illustrator.</li><li>Adobe Premiere Pro.</li><li>Adobe After Effects.</li><li>Canva.</li><li>Figma.</li><li>Herramientas de edición de video y contenido para redes sociales.</li></ul><p>También es una ventaja contar con conocimientos en marketing digital, publicidad online y tendencias de contenido.</p></section>
            <section class="job-section"><h2>Habilidades que pueden ayudarte a destacar ⭐</h2><ul class="job-list"><li>Creatividad e innovación.</li><li>Atención al detalle.</li><li>Organización y gestión del tiempo.</li><li>Trabajo en equipo.</li><li>Adaptabilidad a nuevos proyectos.</li><li>Capacidad para trabajar con fechas de entrega.</li><li>Comunicación efectiva.</li><li>Interés por las tendencias digitales.</li></ul></section>
            <section class="job-section"><h2>Beneficios que podrías obtener 🎁</h2><ul class="job-list"><li>Salario competitivo.</li><li>Prestaciones de ley.</li><li>Capacitación constante.</li><li>Oportunidades de crecimiento profesional.</li><li>Modalidad presencial, híbrida o remota según el proyecto.</li><li>Bonos por desempeño.</li><li>Participación en proyectos creativos de gran impacto.</li><li>Excelente ambiente laboral.</li></ul></section>
            <section class="job-section"><h2>Otras vacantes relacionadas 📌</h2><ul class="job-list job-related-list"><li>Community Manager.</li><li>Diseñador de Contenido para Redes Sociales.</li><li>Editor de Video Digital.</li><li>Especialista en Marketing Digital.</li><li>Diseñador Multimedia.</li><li>Diseñador UI/UX.</li><li>Coordinador de Branding.</li><li>Creador de Contenido Audiovisual.</li></ul></section>
            <section class="job-section"><h2>Recomendaciones para tu postulación 📝</h2><p>Antes de enviar tu candidatura, procura contar con un currículum actualizado y un portafolio que refleje tu experiencia, estilo creativo y habilidades técnicas.</p><ul class="job-list"><li>Incluye ejemplos de trabajos recientes.</li><li>Organiza tu portafolio de manera profesional.</li><li>Destaca proyectos relevantes y resultados obtenidos.</li><li>Investiga previamente sobre la empresa.</li><li>Prepárate para compartir tu proceso creativo durante la entrevista.</li></ul></section>
            <section class="job-section job-cta-section"><h2>Haz crecer tu carrera en el mundo creativo 🚀</h2><p>Las marcas necesitan profesionales capaces de generar contenido que conecte con las personas y fortalezca su presencia digital. Si buscas una oportunidad para demostrar tu talento, desarrollar nuevas habilidades y formar parte de proyectos innovadores, esta vacante puede ser ideal para ti.</p><p>Consulta el enlace de postulación disponible al final de esta publicación y envía tu solicitud. ¡Tu próxima oportunidad profesional podría estar a un solo clic de distancia!</p></section>
            """);
        return config;
    }

    public static PublicacionConfig apoyoDiscapacidadDefault() {
        PublicacionConfig config = apoyoBase("apoyo-discapacidad-permanente", "Pensión", "Apoyo para Personas con Discapacidad Permanente: Conoce los Beneficios y Cómo Solicitarlo ♿💙", "Un respaldo económico para mejorar la calidad de vida", "♿", "Imagen destacada del apoyo para personas con discapacidad permanente");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Un respaldo económico para mejorar la calidad de vida</h2><p>En México existen programas sociales diseñados para brindar apoyo a sectores de la población que enfrentan mayores desafíos en su día a día. Entre ellos destaca el apoyo dirigido a personas con discapacidad permanente, una iniciativa que busca contribuir al bienestar de quienes requieren recursos adicionales para cubrir necesidades esenciales.</p><p>Este beneficio económico tiene como objetivo fortalecer la inclusión social, promover la igualdad de oportunidades y ofrecer un respaldo que permita a los beneficiarios desenvolverse con mayor autonomía dentro de su entorno familiar y comunitario.</p></section>
            <section class="job-section"><h2>¿Cuál es la finalidad de este programa? 🎯</h2><p>El propósito principal es proporcionar un apoyo económico periódico a personas que viven con una discapacidad permanente, ayudándoles a enfrentar gastos relacionados con su bienestar y desarrollo personal.</p><p>Además del respaldo financiero, esta iniciativa busca fomentar una sociedad más incluyente, donde todas las personas tengan acceso a mejores condiciones de vida y mayores oportunidades de participación.</p></section>
            <section class="job-section"><h2>Beneficios que ofrece este apoyo 💙</h2><ul class="job-list check-list"><li>Apoyo económico entregado de forma periódica.</li><li>Mayor estabilidad para cubrir gastos básicos del hogar.</li><li>Ayuda para solventar costos relacionados con salud, rehabilitación o movilidad.</li><li>Fortalecimiento de la independencia personal y familiar.</li><li>Acceso a un programa orientado a la inclusión y el bienestar social.</li><li>Respaldo que contribuye a reducir situaciones de vulnerabilidad económica.</li></ul></section>
            <section class="job-section"><h2>¿Quiénes pueden solicitar este beneficio? 📋</h2><p>Para iniciar el proceso de registro es necesario cumplir con ciertos requisitos establecidos por las autoridades responsables del programa.</p><ul class="job-list"><li>Identificación oficial vigente.</li><li>Acta de nacimiento.</li><li>CURP actualizada.</li><li>Comprobante de domicilio reciente.</li><li>Documento médico o certificado que acredite la discapacidad permanente.</li><li>Formatos de registro proporcionados durante el trámite.</li></ul><p>En caso de que la persona requiera apoyo para realizar el procedimiento, también pueden solicitarse documentos de un auxiliar o representante.</p></section>
            <section class="job-section"><h2>Documentación importante antes de registrarte 🗂️</h2><p>Antes de acudir al módulo correspondiente, es recomendable verificar que todos los documentos se encuentren en buen estado, sean legibles y estén vigentes.</p><p>Contar con la documentación completa puede agilizar considerablemente el proceso y evitar retrasos durante la revisión de la solicitud.</p></section>
            <section class="job-section"><h2>Pasos para realizar tu registro 📝</h2><ol class="job-list"><li>Reúne la documentación requerida y verifica que la información sea correcta.</li><li>Ubica el módulo de atención correspondiente mediante canales oficiales.</li><li>Presenta tu solicitud con los documentos solicitados.</li><li>Espera la validación de datos por parte de las autoridades.</li><li>Da seguimiento a tu trámite y conserva cualquier comprobante o folio.</li><li>Recibe tu medio de pago cuando el registro sea aprobado.</li></ol></section>
            <section class="job-section"><h2>Recomendaciones para facilitar tu trámite ✅</h2><ul class="job-list"><li>Revisa cuidadosamente cada documento antes de presentarlo.</li><li>Mantente informado a través de medios oficiales.</li><li>Conserva copias de toda la documentación entregada.</li><li>Acude puntualmente en las fechas indicadas.</li><li>Solicita orientación en caso de tener dudas sobre algún requisito.</li></ul></section>
            <section class="job-section job-cta-section"><h2>Un apoyo que impulsa la inclusión social 🤝</h2><p>Este programa representa una herramienta importante para miles de personas y familias en todo el país. Su objetivo es brindar un respaldo que contribuya a mejorar las condiciones de vida de quienes viven con una discapacidad permanente, promoviendo al mismo tiempo una sociedad más equitativa e incluyente.</p><p>Si consideras que cumples con los requisitos, consulta la información oficial y revisa el enlace disponible al final de esta publicación para conocer los detalles del proceso de registro.</p></section>
            """);
        return config;
    }

    public static PublicacionConfig saludComunidadDefault() {
        PublicacionConfig config = apoyoBase("salud-en-tu-comunidad", "Salud", "Salud en Tu Comunidad: Atención Médica Más Cerca de las Familias 🏥❤", "Una iniciativa que acerca los servicios de salud a quienes más los necesitan", "🏥", "Imagen destacada del programa Salud en Tu Comunidad");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Una iniciativa que acerca los servicios de salud a quienes más los necesitan</h2><p>Contar con atención médica oportuna puede marcar una gran diferencia en la calidad de vida de las personas. Sin embargo, para muchas familias, trasladarse constantemente a centros de salud representa una dificultad debido a factores económicos, geográficos o de movilidad.</p><p>Por esta razón, se han impulsado programas enfocados en acercar los servicios médicos directamente a los hogares, permitiendo que más personas reciban orientación, seguimiento y atención preventiva sin necesidad de realizar largos desplazamientos.</p><p>Esta estrategia busca fortalecer el bienestar familiar mediante acciones de prevención, detección temprana y acompañamiento profesional, promoviendo una mejor cultura de cuidado de la salud en las comunidades.</p></section>
            <section class="job-section"><h2>¿Cuál es el objetivo de este programa? 🎯</h2><p>La finalidad principal es facilitar el acceso a servicios básicos de salud a través de visitas domiciliarias realizadas por personal capacitado.</p><p>Además de brindar orientación médica, el programa busca identificar factores de riesgo, promover hábitos saludables y acercar información útil para mejorar la salud de todos los integrantes del hogar.</p></section>
            <section class="job-section"><h2>Beneficios para las familias participantes 💚</h2><ul class="job-list check-list"><li>Atención médica básica directamente en el hogar.</li><li>Orientación personalizada sobre hábitos saludables.</li><li>Seguimiento de enfermedades crónicas como diabetes o hipertensión.</li><li>Detección temprana de posibles problemas de salud.</li><li>Apoyo en esquemas de vacunación y prevención.</li><li>Información sobre nutrición, higiene y autocuidado.</li><li>Canalización a servicios especializados cuando sea necesario.</li><li>Acompañamiento para fortalecer el bienestar físico y emocional de las familias.</li></ul></section>
            <section class="job-section"><h2>¿Quiénes pueden ser considerados para recibir este apoyo? 👨‍👩‍👧‍👦</h2><ul class="job-list"><li>Niñas y niños pequeños.</li><li>Mujeres embarazadas.</li><li>Personas adultas mayores.</li><li>Personas con discapacidad.</li><li>Pacientes con enfermedades crónicas que requieren seguimiento constante.</li><li>Familias ubicadas en comunidades con acceso limitado a servicios de salud.</li></ul></section>
            <section class="job-section"><h2>Requisitos generales para participar 📋</h2><ul class="job-list"><li>Identificación oficial vigente.</li><li>CURP.</li><li>Comprobante de domicilio.</li><li>Información básica de los integrantes del hogar.</li><li>Disponibilidad para recibir visitas de seguimiento.</li></ul><p>Es importante verificar los requisitos específicos a través de los canales oficiales correspondientes.</p></section>
            <section class="job-section"><h2>¿Cómo solicitar la incorporación al programa? 📝</h2><ol class="job-list"><li>Consulta la disponibilidad del programa en tu zona.</li><li>Realiza tu registro proporcionando la información solicitada.</li><li>Recibe una visita de valoración en el domicilio.</li><li>Espera la integración al esquema de atención.</li><li>Participa en las visitas y actividades de seguimiento.</li></ol></section>
            <section class="job-section"><h2>Recomendaciones para aprovechar mejor el programa ✅</h2><ul class="job-list"><li>Mantener actualizada la información del hogar.</li><li>Participar activamente durante las visitas.</li><li>Seguir las recomendaciones del personal de salud.</li><li>Informar cualquier cambio importante relacionado con la salud familiar.</li><li>Conservar la documentación solicitada para futuras actualizaciones.</li></ul></section>
            <section class="job-section job-cta-section"><h2>Una apuesta por la prevención y el bienestar 💚</h2><p>Las acciones preventivas continúan siendo una de las herramientas más importantes para mejorar la salud de la población. Programas de atención domiciliaria como este permiten acercar servicios esenciales a las familias, fortalecer la prevención de enfermedades y fomentar una mayor cultura de autocuidado.</p><p>Si deseas conocer más detalles sobre esta iniciativa, consulta la información oficial disponible y revisa el enlace de registro que encontrarás al final de esta publicación.</p></section>
            """);
        return config;
    }

    public static PublicacionConfig adultosMayoresDefault() {
        PublicacionConfig config = apoyoBase("adultos-mayores-registro", "Adultos mayores", "Apoyo para Personas Adultas Mayores: Beneficios, Requisitos y Cómo Realizar tu Registro 👵👴", "Un respaldo pensado para mejorar la calidad de vida", "🧓", "Imagen destacada de apoyo para personas adultas mayores");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Un respaldo pensado para mejorar la calidad de vida</h2><p>Las personas adultas mayores representan una parte fundamental de la sociedad. Después de años de trabajo, experiencia y contribución a sus comunidades, contar con mecanismos de apoyo que favorezcan su bienestar se ha convertido en una prioridad.</p><p>Por ello, existen programas y beneficios orientados a fortalecer la estabilidad económica de este sector de la población, brindando herramientas que les permitan afrontar sus gastos cotidianos con mayor tranquilidad y acceder a diversos servicios que contribuyen a una mejor calidad de vida.</p><p>Además del respaldo económico, estas iniciativas buscan promover la inclusión, la participación social y el acceso a oportunidades que favorezcan una vida más activa e independiente.</p></section>
            <section class="job-section"><h2>¿Qué ventajas ofrece este tipo de apoyo? 🎁</h2><ul class="job-list"><li><strong>Apoyo económico periódico:</strong> recursos para complementar ingresos y cubrir alimentación, transporte, servicios básicos, medicamentos y necesidades personales.</li><li><strong>Acceso a descuentos especiales:</strong> beneficios en comercios, farmacias, transporte público, actividades recreativas, eventos culturales y servicios.</li><li><strong>Facilidades para el cuidado de la salud:</strong> apoyo para atender consultas, tratamientos y seguimiento médico.</li><li><strong>Participación e integración social:</strong> impulso a actividades comunitarias, culturales y recreativas.</li><li><strong>Mayor estabilidad y tranquilidad:</strong> respaldo adicional para afrontar gastos cotidianos con mayor seguridad.</li></ul></section>
            <section class="job-section"><h2>¿Quiénes pueden acceder a estos beneficios? 📋</h2><ul class="job-list check-list"><li>Tener 60 años o más.</li><li>Residir en territorio nacional.</li><li>Presentar documentación oficial vigente.</li><li>Contar con CURP actualizada.</li><li>Acreditar domicilio actual.</li></ul><p>En algunos casos, pueden solicitarse documentos adicionales dependiendo de la modalidad del apoyo o de las disposiciones vigentes.</p></section>
            <section class="job-section"><h2>Documentación requerida 🗂️</h2><ul class="job-list"><li>Identificación oficial vigente.</li><li>CURP certificada.</li><li>Acta de nacimiento.</li><li>Comprobante de domicilio reciente.</li><li>Documentos complementarios que puedan requerirse durante el registro.</li></ul><p>Tener la documentación organizada facilitará la validación de datos y reducirá posibles retrasos.</p></section>
            <section class="job-section"><h2>¿Cómo realizar el trámite? 📝</h2><ol class="job-list"><li>Consulta la información disponible y verifica que cumples con los requisitos.</li><li>Reúne tus documentos en originales y copias.</li><li>Localiza el módulo de atención más cercano.</li><li>Presenta tu solicitud en la fecha y horario indicados.</li><li>Espera la validación de tu expediente.</li><li>Da seguimiento a tu registro conservando folios o comprobantes.</li><li>Recibe la información de tu incorporación una vez aprobado el trámite.</li></ol></section>
            <section class="job-section"><h2>Recomendaciones importantes ✅</h2><ul class="job-list"><li>Verifica que tus documentos estén vigentes.</li><li>Mantén actualizados tus datos personales.</li><li>Consulta únicamente fuentes oficiales.</li><li>Conserva copias de todos los documentos entregados.</li><li>Solicita orientación si tienes dudas sobre algún requisito.</li></ul></section>
            <section class="job-section job-cta-section"><h2>Un apoyo que contribuye al bienestar de miles de familias ❤</h2><p>Los programas dirigidos a personas adultas mayores buscan brindar mayor seguridad, inclusión y bienestar a quienes han dedicado gran parte de su vida al desarrollo de sus familias y comunidades.</p><p>Si deseas conocer más detalles sobre los beneficios disponibles, requisitos actualizados y fechas de atención, consulta la información oficial y revisa el enlace correspondiente al final de esta publicación.</p></section>
            """);
        return config;
    }

    public static PublicacionConfig lecheSubsidiadaDefault() {
        PublicacionConfig config = apoyoBase("leche-subsidiada", "Alimentación", "Nutrición y Apoyo para las Familias: Conoce el Programa de Leche Subsidiada 🥛", "Un respaldo alimentario que marca la diferencia", "🍼", "Imagen destacada del programa de leche subsidiada");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Un respaldo alimentario que marca la diferencia 🥛</h2><p>Contar con una alimentación adecuada es fundamental para el bienestar y el desarrollo de cualquier familia. Con ese objetivo, existe un programa social enfocado en facilitar el acceso a leche fortificada de calidad para personas que pertenecen a sectores prioritarios de la población. Esta iniciativa busca contribuir a una mejor nutrición y, al mismo tiempo, reducir el gasto destinado a productos básicos dentro del hogar.</p><p>A través de una red de distribución establecida en distintas regiones del país, miles de familias pueden adquirir leche enriquecida con vitaminas y minerales esenciales a un costo preferencial. Esto permite que niños, adolescentes, mujeres embarazadas, adultos mayores y personas con condiciones especiales reciban un complemento nutricional importante para su desarrollo y bienestar.</p></section>
            <section class="job-section"><h2>Beneficios principales del programa 💙</h2><ul class="job-list"><li><strong>Leche fortificada de alta calidad:</strong> contiene nutrientes esenciales que favorecen el crecimiento y el fortalecimiento del organismo.</li><li><strong>Ahorro para el hogar:</strong> permite reducir el gasto destinado a productos alimenticios de primera necesidad.</li><li><strong>Apoyo para familias vulnerables:</strong> prioriza a grupos que requieren atención nutricional especial.</li><li><strong>Mejora del desarrollo físico:</strong> favorece el crecimiento saludable de niñas, niños y adolescentes.</li><li><strong>Mayor seguridad alimentaria:</strong> garantiza el acceso constante a un producto nutritivo y accesible.</li><li><strong>Impacto positivo en la calidad de vida:</strong> contribuye al bienestar general de los integrantes del hogar.</li></ul></section>
            <section class="job-section"><h2>¿Quiénes pueden solicitar este apoyo? 📋</h2><p>Para acceder al programa es necesario cumplir con ciertos criterios establecidos para garantizar que el beneficio llegue a quienes realmente lo necesitan.</p><ul class="job-list"><li>Vivir dentro de una zona donde opere el programa.</li><li>Presentar una identificación oficial vigente.</li><li>Contar con un comprobante de domicilio reciente.</li><li>Entregar la documentación correspondiente de los integrantes de la familia.</li><li>Acreditar una situación económica que permita ser considerado dentro de la población objetivo.</li><li>Formar parte de alguno de los grupos prioritarios contemplados por las reglas de operación.</li></ul></section>
            <section class="job-section"><h2>Pasos para realizar el registro 📝</h2><ol class="job-list"><li>Infórmate sobre la cobertura y puntos de atención disponibles.</li><li>Reúne tus documentos, identificaciones y comprobantes.</li><li>Acude al módulo correspondiente para presentar la documentación.</li><li>Completa la solicitud con datos claros y precisos.</li><li>Permite la verificación de información.</li><li>Espera la resolución del registro.</li><li>Comienza a recibir el beneficio en los puntos autorizados si tu solicitud es aceptada.</li></ol></section>
            <section class="job-section job-cta-section"><h2>Una ayuda que fortalece el bienestar familiar 💙</h2><p>Este programa continúa siendo una herramienta importante para apoyar a miles de hogares mediante el acceso a alimentos nutritivos a bajo costo. Gracias a este tipo de iniciativas, muchas familias pueden mejorar su alimentación diaria y contar con un respaldo que contribuye directamente a su bienestar.</p><p>El enlace oficial para consultar información y realizar el proceso correspondiente se encuentra al final de esta página.</p></section>
            """);
        return config;
    }

    public static PublicacionConfig proteccionFamiliasDefault() {
        PublicacionConfig config = apoyoBase("proteccion-familias", "Seguro", "Protección y Apoyo para el Futuro de las Familias ✨", "Una iniciativa pensada para brindar tranquilidad", "👨‍👩‍👧", "Imagen destacada de protección y apoyo para el futuro de las familias");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Una iniciativa pensada para brindar tranquilidad</h2><p>La estabilidad de una familia depende, en gran medida, de quienes día a día trabajan para sacar adelante a sus hijos. Conscientes de esta realidad, existen programas sociales enfocados en ofrecer respaldo a los hogares encabezados por madres responsables del sustento familiar. Su finalidad es brindar protección económica a los hijos e hijas en caso de que ocurra una situación inesperada que afecte a la principal proveedora del hogar.</p><p>Esta iniciativa busca que niñas, niños y jóvenes puedan continuar con su formación académica y mantener mejores condiciones de bienestar, evitando que la falta de recursos económicos limite sus oportunidades de desarrollo personal y educativo.</p></section>
            <section class="job-section"><h2>Beneficios principales del programa 💙</h2><ul class="job-list"><li><strong>Apoyo para la educación:</strong> busca que los beneficiarios continúen estudiando sin interrupciones por motivos económicos.</li><li><strong>Respaldo económico periódico:</strong> ayuda financiera para necesidades relacionadas con la formación y el desarrollo de los hijos.</li><li><strong>Protección para el núcleo familiar:</strong> brinda mayor seguridad ante situaciones imprevistas.</li><li><strong>Mayor estabilidad económica:</strong> reduce el impacto financiero que puede enfrentar el hogar en circunstancias difíciles.</li><li><strong>Impulso al desarrollo de niñas, niños y jóvenes:</strong> favorece sus metas académicas y proyecto de vida.</li><li><strong>Tranquilidad para las madres de familia:</strong> representa una garantía importante para el futuro de sus hijos.</li></ul></section>
            <section class="job-section"><h2>Requisitos generales para participar 📋</h2><ul class="job-list"><li>Identificación oficial vigente.</li><li>Acta de nacimiento de los hijos o dependientes.</li><li>Comprobante de domicilio reciente.</li><li>Datos de contacto actualizados.</li><li>Información que acredite la integración familiar.</li><li>Formato de registro debidamente completado.</li><li>Constancias o documentos relacionados con la situación educativa de los menores, cuando sean requeridos.</li></ul></section>
            <section class="job-section"><h2>Cómo realizar el registro 📝</h2><ol class="job-list"><li>Consulta la información oficial y convocatorias vigentes.</li><li>Reúne tu documentación y verifica que esté actualizada.</li><li>Completa tu solicitud con los datos personales y familiares requeridos.</li><li>Presenta tus documentos en módulos, oficinas o plataformas autorizadas.</li><li>Espera la validación de las autoridades.</li><li>Da seguimiento a tu trámite conservando tu folio o comprobante.</li></ol></section>
            <section class="job-section job-cta-section"><h2>Un apoyo que busca construir mejores oportunidades 💙</h2><p>Este tipo de programas representan una importante herramienta de protección social para miles de familias. Su objetivo es fortalecer el bienestar de los menores y contribuir a que continúen desarrollando sus capacidades académicas y personales, incluso frente a situaciones difíciles.</p><p>Al final de esta página podrás encontrar el enlace oficial donde consultar información actualizada y realizar el proceso correspondiente.</p></section>
            """);
        return config;
    }

    public static PublicacionConfig reconstruyendoComunidadesDefault() {
        PublicacionConfig config = apoyoBase("reconstruyendo-comunidades", "Vivienda", "Reconstruyendo Comunidades: Apoyo para la Recuperación de Zonas Afectadas 🏡", "Una iniciativa para recuperar hogares y espacios esenciales", "🏢", "Imagen destacada de apoyo para la recuperación de zonas afectadas");
        config.setContenidoHtml("""
            <section class="job-section job-intro-card"><h2>Una iniciativa para recuperar hogares y espacios esenciales</h2><p>Cuando una comunidad enfrenta los efectos de un fenómeno natural, las consecuencias pueden afectar viviendas, escuelas, centros de salud y servicios básicos. Con el objetivo de impulsar la recuperación de estas zonas, existen programas de apoyo enfocados en la rehabilitación de infraestructura y el fortalecimiento de las condiciones de vida de las familias afectadas.</p><p>Estas acciones buscan no solo reparar los daños ocasionados, sino también promover soluciones más seguras y duraderas que permitan a las comunidades afrontar futuros desafíos con una mejor preparación.</p></section>
            <section class="job-section"><h2>¿Qué beneficios puede ofrecer este apoyo? 🏗️</h2><ul class="job-list"><li><strong>Mejoramiento y rehabilitación de viviendas:</strong> apoyo destinado a la reparación o reconstrucción de inmuebles afectados.</li><li><strong>Recuperación de espacios educativos:</strong> restauración de escuelas y centros de aprendizaje.</li><li><strong>Fortalecimiento de servicios de salud:</strong> mejoras en clínicas, centros médicos e instalaciones de atención comunitaria.</li><li><strong>Rehabilitación de infraestructura pública:</strong> recuperación de caminos, puentes y vías de acceso.</li><li><strong>Restablecimiento de servicios básicos:</strong> acciones para mejorar agua potable, energía eléctrica y saneamiento.</li><li><strong>Conservación de espacios históricos y culturales:</strong> restauración de inmuebles representativos.</li><li><strong>Participación ciudadana:</strong> integración de la comunidad en la recuperación y seguimiento.</li><li><strong>Desarrollo sostenible:</strong> soluciones que favorecen la seguridad y resiliencia de las zonas beneficiadas.</li></ul></section>
            <section class="job-section"><h2>Requisitos generales para participar 📋</h2><ul class="job-list"><li>Identificación oficial vigente.</li><li>Comprobante de domicilio actualizado.</li><li>Documentación relacionada con la propiedad o posesión del inmueble.</li><li>Residir en una zona considerada dentro de los esquemas de atención del programa.</li><li>Registro o inclusión dentro de censos, evaluaciones o levantamientos oficiales.</li><li>Información socioeconómica cuando sea requerida para el análisis de la solicitud.</li><li>Disposición para colaborar durante los procesos de verificación y seguimiento.</li></ul></section>
            <section class="job-section"><h2>Cómo realizar tu solicitud 📝</h2><ol class="job-list"><li>Consulta la información disponible sobre convocatorias, zonas de cobertura y requisitos.</li><li>Prepara tu documentación y verifica que sea legible y actualizada.</li><li>Registra tu solicitud en módulos, oficinas o plataformas habilitadas.</li><li>Permite la evaluación correspondiente mediante visitas o inspecciones.</li><li>Espera la validación del expediente.</li><li>Recibe la notificación de resultados.</li><li>Da seguimiento al apoyo otorgado y a la supervisión de las acciones de reconstrucción.</li></ol></section>
            <section class="job-section job-cta-section"><h2>Un paso importante hacia la recuperación 💙</h2><p>La reconstrucción de viviendas, servicios e infraestructura representa una oportunidad para fortalecer a las comunidades afectadas y mejorar sus condiciones de vida. Este tipo de iniciativas buscan impulsar una recuperación ordenada y sostenible, brindando apoyo a quienes enfrentan las consecuencias de eventos que impactan su entorno y patrimonio.</p><p>Al final de esta página encontrarás el enlace oficial para consultar información actualizada y conocer los procedimientos vigentes.</p></section>
            """);
        return config;
    }

    private static PublicacionConfig base(String slug, String categoria, String titulo, String subtitulo, String icono, String heroImageAlt) {
        PublicacionConfig config = new PublicacionConfig();
        config.setSlug(slug);
        config.setCategoria(categoria);
        config.setTitulo(titulo);
        config.setSubtitulo(subtitulo);
        config.setIcono(icono);
        config.setHeroImageUrl("");
        config.setHeroImageAlt(heroImageAlt);
        config.setPostulationUrl(DEFAULT_URL);
        config.setButtonLabel("Más información");
        config.setCierrePostulacion("Consulta el enlace de postulación disponible al final de esta publicación y envía tu candidatura.");
        return config;
    }

    private static PublicacionConfig apoyoBase(String slug, String categoria, String titulo, String subtitulo, String icono, String heroImageAlt) {
        PublicacionConfig config = base(slug, categoria, titulo, subtitulo, icono, heroImageAlt);
        config.setCierrePostulacion("Consulta el enlace oficial disponible al final de esta publicación para revisar la información actualizada y continuar con el proceso correspondiente.");
        return config;
    }
}
