CREATE TABLE IF NOT EXISTS empresas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    telefono VARCHAR(30),
    correo VARCHAR(150),
    usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasenia VARCHAR(120) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'activo'
);

CREATE TABLE IF NOT EXISTS agentes (
    id_agente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_agente VARCHAR(120) NOT NULL,
    telefono_agente VARCHAR(30),
    usuario_agente VARCHAR(50) NOT NULL UNIQUE,
    contrasenia_agente VARCHAR(120) NOT NULL,
    id_empresa INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tipificaciones (
    id_tipo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motivo_tipo VARCHAR(120) NOT NULL,
    descripcion_tipo VARCHAR(255),
    id_empresa INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS llamadas (
    id_llamada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente VARCHAR(120) NOT NULL,
    telefono_cliente VARCHAR(30),
    fecha_llamada VARCHAR(20),
    hora VARCHAR(10),
    id_agente INTEGER NOT NULL DEFAULT 1,
    id_tipo INTEGER NOT NULL,
    motivo_tipo VARCHAR(120)
);
